#!/usr/bin/env ruby
#^syntax detection

site 'https://community.opscode.com/api/v1'

cookbook 'vagrant',
  :git => 'https://github.com/noahgibbs/vagrant-cookbook', :ref => "v0.0.29"
cookbook 'virtualbox',
  :git => 'https://github.com/noahgibbs/virtualbox-cookbook', :ref => "v0.0.29"
