#!/usr/bin/env ruby
#^syntax detection

site 'https://community.opscode.com/api/v1'

# TODO: lock down Vagrant and VirtualBox cookbooks at specific release version

cookbook 'vagrant',
  :git => 'https://github.com/noahgibbs/vagrant-cookbook'
cookbook 'virtualbox',
  :git => 'https://github.com/noahgibbs/virtualbox-cookbook'
